version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: campus_trade_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ld123456
      MYSQL_DATABASE: campus_trade
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/campus_trade.sql:/docker-entrypoint-initdb.d/campus_trade.sql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-time-zone=+8:00",
        "--lower-case-table-names=1",
        "--default-authentication-plugin=mysql_native_password",
      ]

volumes:
  mysql_data:
