# Generated by Django 5.0 on 2026-05-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '物品分类',
                'verbose_name_plural': '物品分类',
                'db_table': 'category',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('item_type', models.CharField(choices=[('lost', '寻物启事'), ('found', '招领启事')], max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('active', '已发布'), ('resolved', '已完成'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('location', models.CharField(max_length=200, verbose_name='地点')),
                ('item_time', models.DateTimeField(help_text='遗失或发现的时间', verbose_name='物品时间')),
                ('contact_name', models.CharField(max_length=50, verbose_name='联系人')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='悬赏金额')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='图片1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='图片2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='图片3')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.category', verbose_name='物品分类')),
            ],
            options={
                'verbose_name': '物品信息',
                'verbose_name_plural': '物品信息',
                'db_table': 'item',
                'ordering': ['-created_at'],
            },
        ),
    ]
