server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allow-credentials: true
            max-age: 3600
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**

        - id: logistics-service
          uri: lb://logistics-service
          predicates:
            - Path=/api/logistics/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: debug
