version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: admin-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ld123456
      MYSQL_DATABASE: admin_system
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
