# Generated by Django 5.0 on 2026-05-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='描述物品特征等证明信息', verbose_name='认领说明')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已确认'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '认领申请',
                'verbose_name_plural': '认领申请',
                'db_table': 'claim',
                'ordering': ['-created_at'],
            },
        ),
    ]
