# Generated by Django 5.0 on 2026-05-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='罚款金额')),
                ('overdue_days', models.IntegerField(default=0, verbose_name='逾期天数')),
                ('reason', models.TextField(verbose_name='罚款原因')),
                ('status', models.CharField(choices=[('unpaid', '未支付'), ('paid', '已支付'), ('waived', '已豁免')], default='unpaid', max_length=20, verbose_name='支付状态')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='支付日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '罚款记录',
                'verbose_name_plural': '罚款记录',
                'db_table': 'fines',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, verbose_name='借阅日期')),
                ('due_date', models.DateTimeField(verbose_name='应还日期')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='实际归还日期')),
                ('renew_count', models.IntegerField(default=0, verbose_name='续借次数')),
                ('max_renew_count', models.IntegerField(default=2, verbose_name='最大续借次数')),
                ('status', models.CharField(choices=[('borrowed', '借阅中'), ('returned', '已归还'), ('overdue', '已逾期'), ('renewed', '已续借')], default='borrowed', max_length=20, verbose_name='借阅状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='借阅图书')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'db_table': 'borrow_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
