# Generated by Django 5.0 on 2026-05-03 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to=settings.AUTH_USER_MODEL, verbose_name='借阅人'),
        ),
        migrations.AddField(
            model_name='fine',
            name='borrow_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='borrows.borrowrecord', verbose_name='借阅记录'),
        ),
        migrations.AddField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
